version: '3.8'

services:
  imobiauto:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-imoveis
    restart: always
    ports:
      - "8080:80"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-${API_KEY}}
      - PORT=80
